"""add savings_vaults table

Revision ID: 077063a8d41f
Revises: 842eec630af9
Create Date: 2026-09-06 21:52:06.988821

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '077063a8d41f'
down_revision: Union[str, Sequence[str], None] = '842eec630af9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('savings_vaults',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('target_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('current_amount', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False),
    sa.Column('lock_until', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('active', 'locked_complete', 'broken', 'withdrawn', name='vault_status'), server_default='active', nullable=False),
    sa.Column('milestone_tier', sa.String(), nullable=False),
    sa.Column('cooling_off_requested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('milestones_reached', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_savings_vaults_user_id'), 'savings_vaults', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_savings_vaults_user_id'), table_name='savings_vaults')
    op.drop_table('savings_vaults')
    # ### end Alembic commands ###
