"""add status to savings_transactions

Revision ID: 0bf1acfafb73
Revises: 5e8d6062156c
Create Date: 2026-09-08 15:28:40.866798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0bf1acfafb73'
down_revision: Union[str, Sequence[str], None] = '5e8d6062156c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    transaction_status = sa.Enum(
        'pending', 'success', 'failed', name='transaction_status'
    )
    transaction_status.create(op.get_bind(), checkfirst=True)
    op.add_column(
        'savings_transactions',
        sa.Column(
            'status',
            transaction_status,
            server_default='success',
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('savings_transactions', 'status')
    sa.Enum(name='transaction_status').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
