"""add checkins_enabled to users

Revision ID: 17c5b988b5ed
Revises: 89bc214e3a37
Create Date: 2026-08-10 20:07:29.417328

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17c5b988b5ed'
down_revision: Union[str, Sequence[str], None] = '89bc214e3a37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('checkins_enabled', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'checkins_enabled')
    # ### end Alembic commands ###
