"""empty message

Revision ID: 2b284998a54d
Revises: c5e6fd88af74
Create Date: 2026-08-07 20:05:03.596734

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2b284998a54d'
down_revision: Union[str, Sequence[str], None] = 'c5e6fd88af74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_usage_logs', sa.Column('usage_date', sa.Date(), nullable=False))
    op.add_column('ai_usage_logs', sa.Column('request_count', sa.Integer(), server_default='0', nullable=False))
    op.create_index(op.f('ix_ai_usage_logs_usage_date'), 'ai_usage_logs', ['usage_date'], unique=False)
    op.create_index(op.f('ix_ai_usage_logs_user_id'), 'ai_usage_logs', ['user_id'], unique=False)
    op.create_unique_constraint('uq_user_usage_date', 'ai_usage_logs', ['user_id', 'usage_date'])
    op.drop_constraint(op.f('ai_usage_logs_user_id_fkey'), 'ai_usage_logs', type_='foreignkey')
    op.create_foreign_key(None, 'ai_usage_logs', 'users', ['user_id'], ['id'])
    op.drop_column('ai_usage_logs', 'action')
    op.drop_column('ai_usage_logs', 'tokens_used')
    op.drop_column('ai_usage_logs', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_usage_logs', sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('ai_usage_logs', sa.Column('tokens_used', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('ai_usage_logs', sa.Column('action', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'ai_usage_logs', type_='foreignkey')
    op.create_foreign_key(op.f('ai_usage_logs_user_id_fkey'), 'ai_usage_logs', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('uq_user_usage_date', 'ai_usage_logs', type_='unique')
    op.drop_index(op.f('ix_ai_usage_logs_user_id'), table_name='ai_usage_logs')
    op.drop_index(op.f('ix_ai_usage_logs_usage_date'), table_name='ai_usage_logs')
    op.drop_column('ai_usage_logs', 'request_count')
    op.drop_column('ai_usage_logs', 'usage_date')
    # ### end Alembic commands ###
