"""add payout recipient fields to users

Revision ID: 5e8d6062156c
Revises: b4a747fad872
Create Date: 2026-09-08 12:10:03.804195

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e8d6062156c'
down_revision: Union[str, Sequence[str], None] = 'b4a747fad872'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('paystack_recipient_code', sa.String(), nullable=True))
    op.add_column('users', sa.Column('payout_bank_code', sa.String(), nullable=True))
    op.add_column('users', sa.Column('payout_account_number', sa.String(), nullable=True))
    op.add_column('users', sa.Column('payout_account_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'payout_account_name')
    op.drop_column('users', 'payout_account_number')
    op.drop_column('users', 'payout_bank_code')
    op.drop_column('users', 'paystack_recipient_code')
    # ### end Alembic commands ###
