"""add snoozed_until to tasks

Revision ID: 73eae5e97e2f
Revises: 61714113a2ce
Create Date: 2026-07-19 11:53:05.160282

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73eae5e97e2f'
down_revision: Union[str, Sequence[str], None] = '61714113a2ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('snoozed_until', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'snoozed_until')
    # ### end Alembic commands ###
