"""add is_reminder_sent to tasks

Revision ID: 87ef777eef77
Revises: 09f12da7ddf3
Create Date: 2026-07-26 11:30:55.270789

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87ef777eef77'
down_revision: Union[str, Sequence[str], None] = '09f12da7ddf3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('is_reminder_sent', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'is_reminder_sent')
    # ### end Alembic commands ###
