"""add user dva fields and pending_deposits table

Revision ID: aa5a9838291c
Revises: 077063a8d41f
Create Date: 2026-09-06 23:00:42.645421

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa5a9838291c'
down_revision: Union[str, Sequence[str], None] = '077063a8d41f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pending_deposits',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('vault_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('expected_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.Enum('pending', 'matched', 'expired', name='pending_deposit_status'), server_default='pending', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vault_id'], ['savings_vaults.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pending_deposits_user_id'), 'pending_deposits', ['user_id'], unique=False)
    op.create_index(op.f('ix_pending_deposits_vault_id'), 'pending_deposits', ['vault_id'], unique=False)
    op.add_column('users', sa.Column('paystack_customer_code', sa.String(), nullable=True))
    op.add_column('users', sa.Column('dva_account_number', sa.String(), nullable=True))
    op.add_column('users', sa.Column('dva_bank_name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('dva_account_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'dva_account_name')
    op.drop_column('users', 'dva_bank_name')
    op.drop_column('users', 'dva_account_number')
    op.drop_column('users', 'paystack_customer_code')
    op.drop_index(op.f('ix_pending_deposits_vault_id'), table_name='pending_deposits')
    op.drop_index(op.f('ix_pending_deposits_user_id'), table_name='pending_deposits')
    op.drop_table('pending_deposits')
    # ### end Alembic commands ###
