"""add savings_transactions table

Revision ID: b4a747fad872
Revises: aa5a9838291c
Create Date: 2026-09-07 16:33:30.312588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4a747fad872'
down_revision: Union[str, Sequence[str], None] = 'aa5a9838291c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('savings_transactions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('vault_id', sa.Uuid(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('type', sa.Enum('deposit', 'withdrawal', name='transaction_type'), nullable=False),
    sa.Column('paystack_reference', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vault_id'], ['savings_vaults.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_savings_transactions_paystack_reference'), 'savings_transactions', ['paystack_reference'], unique=True)
    op.create_index(op.f('ix_savings_transactions_user_id'), 'savings_transactions', ['user_id'], unique=False)
    op.create_index(op.f('ix_savings_transactions_vault_id'), 'savings_transactions', ['vault_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_savings_transactions_vault_id'), table_name='savings_transactions')
    op.drop_index(op.f('ix_savings_transactions_user_id'), table_name='savings_transactions')
    op.drop_index(op.f('ix_savings_transactions_paystack_reference'), table_name='savings_transactions')
    op.drop_table('savings_transactions')
    # ### end Alembic commands ###
