"""add goal_status to checkins

Revision ID: bd903a85c65f
Revises: 17c5b988b5ed
Create Date: 2026-08-15 09:53:59.654581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd903a85c65f'
down_revision: Union[str, Sequence[str], None] = '17c5b988b5ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('checkins', sa.Column('goal_status', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('checkins', 'goal_status')
    # ### end Alembic commands ###
