"""add kyc fields, payout fields, expand vault status

Revision ID: ee417641f046
Revises: 6c2d9e7f4a11
Create Date: 2026-09-09 10:55:25.534884

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'ee417641f046'
down_revision: Union[str, Sequence[str], None] = '6c2d9e7f4a11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    kyc_status = postgresql.ENUM(
        'unverified', 'pending', 'verified', 'failed',
        name='kyc_status',
    )
    kyc_status.create(op.get_bind(), checkfirst=True)
    op.add_column(
        'users',
        sa.Column(
            'kyc_status',
            postgresql.ENUM(
                'unverified', 'pending', 'verified', 'failed',
                name='kyc_status',
                create_type=False,
            ),
            server_default='unverified',
            nullable=False,
        ),
    )
    op.add_column('users', sa.Column('kyc_verified_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'kyc_verified_name')
    op.drop_column('users', 'kyc_status')
    op.execute("DROP TYPE IF EXISTS kyc_status")
    # ### end Alembic commands ###
